### ISSUE TITLE
Search season packs when searching for specific episode

### ISSUE THREAD

**Issue by tstrul1** [mancuniancol/script.provider.quasar.manager#1]
Old episodes usually doesnt have a lot of seeders to download speed is slow but season packs has more seeders.
Please consider adding the option to search the relevant season pack when searching for  a single episode.

**Comment by mancuniancol** [comment]
This is just for providers. I am not part of Quasar developpers. Please any requests for Quasar, it should address to them. 
And I think your request was already implemented. 
https://github.com/scakemyer/plugin.video.quasar/issues/17

**Comment by tstrul1** [comment]
I didnt mean that. I know quasar is able to deal with season packs but i want that search results for single episode will include season packs... @scakemyer commented about this issue "This is working as intended, it's now up to providers to return results with season packs or give different options for those"  (https://github.com/scakemyer/plugin.video.quasar/issues/116)

**Comment by mancuniancol** [comment]
Version 1.1.0 is season ready. If you have problem with a specific provider, please, describe it in detail and share the debug kodi log in the respective provider. This is only for provider manager.
