### ISSUE TITLE
manager not working with new version of providers

### ISSUE THREAD

**Issue by ShlomiD83** [mancuniancol/script.provider.quasar.manager#2]
will this be updated to?

**Comment by mancuniancol** [comment]
I will need your kodi log in debug mode using the manager to see the problem. You can share the log with pastebin.com or another site

**Comment by ShlomiD83** [comment]
http://pastebin.com/9R7aUGUC

**Comment by mancuniancol** [comment]
Usually, I check logs from bugs the weekend. I add your case to my list. I will contact you when I have an answer

**Comment by mancuniancol** [comment]
I cannot find any trouble with the manager.  Could you be more specific? Could you tell me what you change that it is not reflected in the providers?

**Comment by ShlomiD83** [comment]
im making changes in the manager and not getting the notification that changes were made like with the previous version of the providers, and it changes nothing in the providers settings. maybe i didnt make a proper debug log? i can try again..

**Comment by mancuniancol** [comment]
Please, because in my side it works. If I cannot reproduce your issue. I cannot help you

**Comment by ShlomiD83** [comment]
opened a new kodi copy and installed quasar, manager and 3 providers. here's my log.

http://pastebin.com/hFrdagNp

**Comment by mancuniancol** [comment]
OK, I will check this weekend

**Comment by rosskopf** [comment]
Hi,
i had the same problem but i found that if u rename the providers in ~/.kodi/addons from script.quasar.torlock-mc1.1.0 to script.quasar.torlock-mc that it works 
it need to ends with "-mc"

**Comment by mancuniancol** [comment]
I will check that I've been really busy. I didn't have enough time to fix it yet

**Comment by ShlomiD83** [comment]
Thought about renaming the folders but that didn't work either ..

**Comment by ShlomiD83** [comment]
Hello again, i don't want to bother you but i have another problem, providers aren't sending results to quasar and rarbg is getting ERROR parsing data.

http://pastebin.com/88eVpQ2y

sorry if i'm not in the right place, didnt know where to post this.

**Comment by mancuniancol** [comment]
Well, I need to rewrite the providers to complain with the new Quasar's specifications.  Then, it will take some time until I can work in the manager. :p  But, eventually, I will fix it.

**Comment by ShlomiD83** [comment]
ok, thank you.

**Comment by ShlomiD83** [comment]
I'm also getting better results with only one provider (kickass)  than with 2 or 3 (kickass & rarbg) (kickass & rarbg & torrentz). Will rewriting them sort this also?

**Comment by mancuniancol** [comment]
No, that it will be your Quasar configuration. Increase your time out

**Comment by ShlomiD83** [comment]
Increased it to 10 seconds and it seems it's ok now, thanks..
